### ISSUE TITLE
Trouble with routing nuxt pages

### ISSUE THREAD

**Issue by ll931217** [vuchl/nuxt-micro-template#9]
I migrated my app from using express to micro, my API routes work fine but I can't seem to get my `nuxt.render(req, res)` to work.

This is my routes:
```javascript
module.exports = (nuxt) => {
  return async (req, res) => {
    await dispatch()
      .dispatch('/api/echo', 'POST', echo)

      .dispatch('/api/users/register', 'POST', register)
      .dispatch('/api/users/login', 'POST', login)
      .dispatch('/api/users/edit', 'POST', editUser)

      .dispatch('/api/eracks', 'POST', newRack)
      .dispatch('/api/eracks/import', 'POST', importRacks)

      .dispatch('/api/logs/read', 'POST', readLog)
      .dispatch('/api/logs/all', 'POST', clearAllLogs)

      .dispatch('/api/carriers', 'POST', pushCarrier)

      .dispatch('/api/carriers', 'GET', getCarriers)
      .dispatch('/api/carriers/:id', 'GET', getCarrier)

      .dispatch('/api/users', 'DELETE', deleteUser)

      .dispatch('/api/eracks', 'DELETE', deleteRack)

      .dispatch('/api/logs', 'DELETE', deleteLog)

      .dispatch('/api/eracks', 'GET', getRacks)
      .dispatch('/api/eracks/:mac', 'GET', getRack)

      .dispatch('/api/configs', 'GET', getConfigs)
      .dispatch('/api/configs/sizes', 'GET', getSizes)

      .dispatch('/api/users/:id', 'GET', getUser)
      .dispatch('/api/users', 'GET', getUsers)

      .dispatch('/api/logs', 'GET', getLogs)

      .dispatch('*', 'GET', (req, res) => nuxt.render(req, res))(req, res)
  }
}
```
`nuxt` is passed from `index.js`:
```javascript
const nuxt = new Nuxt(config)

if (nuxt.options.dev) {
  await new Builder(nuxt).build()
} else {
  await nuxt.ready()
}

const server = micro(routes(nuxt))
```

What happens when I try load any route that is to one of my pages, the browser tab spinner just keeps spinning. However, when I use postman to request data from my server, it works.

I tried changing `micro-route` to a more popular module [`micro-router`](https://github.com/pedronauck/micro-router), it somehow rendered but in the terminal it keeps saying:

```bash
(node:15776) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at sendResponse (D:\Liang\LeetManjaro\Work\micro-nuxt\node_modules\@nuxt\server\dist\server.js:273:9)
    at errorMiddleware (D:\Liang\LeetManjaro\Work\micro-nuxt\node_modules\@nuxt\server\dist\server.js:333:5)
(node:15776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 47871)
```

and a `NuxtServerError` page:
![Capture](https://user-images.githubusercontent.com/12750413/57824720-95b2c480-77ce-11e9-94c6-02462e2df5fc.PNG)

**Comment by ll931217** [comment]
Sorry, I fixed it. It was nuxtServerInit issue. Somehow it is being called multiple times, not sure why.
